Rename script generate-git-ctags to generate-project-tags

diff --git a/common/bin/generate-project-tags b/common/bin/generate-project-tags
--- a/common/bin/generate-project-tags
+++ b/common/bin/generate-project-tags
@@ -11,8 +11,8 @@ trap 'rm -f "$$.tags"' EXIT
 
 # Check if we're in a git repository
 if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-  echo "Error: Not inside a Git repository. Please run this script inside a Git repository." >&2
-  exit 1
+	echo "Error: Not inside a Git repository. Please run this script inside a Git repository." >&2
+	exit 1
 fi
 
 # Navigate to the root of the git repository
